networks:
  postgres-backend:
    external: true

services:
  consul:
    image: consul:1.13
    hostname: consul1
    environment:
      TZ: Asia/Tashkent
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./data/consul:/consul/data
    restart: unless-stopped
    networks:
      postgres-backend:
        ipv4_address: 172.18.0.10



#    command: agent -server -advertise 10.128.0.18 -bootstrap-expect 3 -client 0.0.0.0 -retry-join 10.128.0.18 -retry-join 10.128.0.98 -retry-join 10.128.0.99
